# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskselection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
