# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskselection', '0002_task_is_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
