# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskselection', '0003_auto_20170921_0815'),
    ]

    operations = [
    ]
