# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskselection', '0004_auto_20170928_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_sticky',
        ),
        migrations.AddField(
            model_name='task',
            name='_is_sticky',
            field=models.BooleanField(db_column='is_sticky', default=False),
        ),
    ]
